spring.application.name=mspagos

# Puerto del microservicio
server.port=8084

# ==========================
# MYSQL (Laragon)
# ==========================

spring.datasource.url=jdbc:mysql://localhost:3306/mspagos
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================
# COMUNICACION ENTRE MICROSERVICIOS
# ==========================
# URL base del microservicio de Pedidos.
# Se utiliza para notificar el estado del pago sobre el pedido asociado.

microservicio.pedidos.url=http://localhost:8083/pedidos
